version: '2.2'

services:
    elasticsearch:
        build:
            # 현재 경로에서 Dockerfile을 위치할 경로
            context: elasticsearch/
        # 컨테이너 이름
        container_name: es01
        environment:
            - node.name=ubuntu-es
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms4g -Xmx4g"  # <== JAVA heap memory setting
        ulimits:
            memlock:
                soft: -1
                hard: -1
        # volume을 아래와 같이 구성 가능        
        volumes:    # ==> Data Mount
            # 현재 소스파일을 docker system으로 연동시키는 방법 --> 이 command를 활용하면 Dockerfile에서 굳이 COPY할 필요 없다.
            - type: bind
              source: elasticsearch/analysis/test.txt
              target: /usr/share/elasticsearch/config/analysis/synonym.txt
              read_only: true
            # 아래 표현의 축약형 == - data01:/usr/share/elasticsearch/data
            - type: volume
              source: data01
              target: /usr/share/elasticsearch/data
            
        ports:
            - 9200:9200
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.7
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_HOSTS=["http://es01:9200"]
        depends_on:
            - elasticsearch
        networks:
            - elastic

volumes:
    data01:
        driver: local

networks:
    elastic: